name: Auto PR to master

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Select the source branch to create the PR from'
        type: choice
        required: true
        default: webdev0065-patch-1
        options:
          - webdev0065-patch-1
          - another-feature-branch
          - hotfix-123
      draft:
        description: 'Create pull request as a draft?'
        type: boolean
        required: true
        default: false

permissions:
  contents: write
  pull-requests: write

jobs:
  create-pull-request:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: master
          head: ${{ inputs.branch }}
          title: "Auto PR from ${{ inputs.branch }} to master"
          body: |
            This PR was automatically created by GitHub Actions.
            Changes from `${{ inputs.branch }}` will be merged into `master`.
          draft: ${{ inputs.draft }}
