name: Auto PR to master

on:
  workflow_dispatch:
    inputs:
      exported_resources_env:
        description: 'Source environment where resources (e.g., flows, scripts) were originally exported from'
        required: true
        type: choice
        options:
          - 'dev'
          - 'uat'
          - 'train'
          - 'prod'
        default: 'dev'

      plan-apply-option:
        description: 'Choose to plan and apply or only see the plan'
        required: true
        type: choice
        options:
          - 'plan and apply'
          - 'plan only'
        default: 'plan and apply'

      target_env:
        description: 'Target environment to plan/apply to'
        required: true
        type: choice
        options:
          - 'dev'
          - 'uat'
          - 'train'
          - 'prod'
        default: 'dev'

      draft:
        description: 'Create pull request as draft?'
        required: true
        type: boolean
        default: false

permissions:
  contents: write
  pull-requests: write

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
       
