name: Auto PR to New Branch

on:
  push:
    branches:
      - webdev0065-patch-1
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  create-new-branch-and-merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Git user
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Generate new branch name
        id: branch
        run: |
          export NEW_BRANCH="auto/pr-$(date +'%Y-%m-%d-%H%M%S')"
          echo "branch_name=$NEW_BRANCH" >> $GITHUB_OUTPUT

      - name: Create and push new branch
        run: |
          git fetch origin
          git checkout -b ${{ steps.branch.outputs.branch_name }}
          git push origin ${{ steps.branch.outputs.branch_name }}

      - name: Merge patch branch into new branch
        run: |
          git fetch origin webdev0065-patch-1
          git merge origin/webdev0065-patch-1 --no-edit
          git push origin ${{ steps.branch.outputs.branch_name }}

      - name: Create Pull Request (optional)
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: ${{ steps.branch.outputs.branch_name }}
          head: webdev0065-patch-1
          title: 'Auto PR from webdev0065-patch-1 to ${{ steps.branch.outputs.branch_name }}'
          body: |
            This PR merges changes from `webdev0065-patch-1` into `${{ steps.branch.outputs.branch_name }}`
          draft: false
