name: Auto PR to master

on:
  push:
    branches:
      - webdev0065-patch-1

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: master
          head: webdev0065-patch-1
          title: 'Auto PR from webdev0065-patch-1 to master'
          body: |
            This PR was automatically created by GitHub Actions
            to merge changes from `webdev0065-patch-1` into `master`.
          draft: false
