name: Auto PR to master

on:
  workflow_dispatch:
inputs:
      exported_resources_env:
        description: 'Source environment where resources (e.g., flows, scripts) were originally exported from (Select environment you exported from previously, else choose same option as target environment)'
        required: true
        type: choice
        options:
          - 'dev'
          - 'uat'
          - 'train'
          - 'prod'
        default: 'N/A'
      plan-apply-option:
        description: 'Choose to plan and apply or only see the plan (no manual validation required)'
        required: true
        type: choice
        options:
          - 'plan and apply'
          - 'plan only'
        default: 'plan and apply'
      target_env:
        description: 'Target environment to plan/ apply to (will require manual validation if applying too)'
        required: true
        type: choice
        options:
          - 'dev'
          - 'uat'
          - 'train'
          - 'prod'
        default: 'N/A'

permissions:
  contents: write
  pull-requests: write

jobs:
  create-pull-request:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: master
          head: ${{ inputs.branch }}
          title: "Auto PR from ${{ inputs.branch }} to master"
          body: |
            This PR was automatically created by GitHub Actions.
            Changes from `${{ inputs.branch }}` will be merged into `master`.
          draft: ${{ inputs.draft }}
