name: Auto PR to master

on:
  workflow_dispatch:
    inputs:
      exported_resources_env:
        description: 'Source environment where resources (e.g., flows, scripts) were originally exported from'
        required: true
        type: choice
        options:
          - 'dev'
          - 'uat'
          - 'train'
          - 'prod'
        default: 'dev'

      plan-apply-option:
        description: 'Choose to plan and apply or only see the plan'
        required: true
        type: choice
        options:
          - 'plan and apply'
          - 'plan only'
        default: 'plan and apply'

      target_env:
        description: 'Target environment to plan/apply to'
        required: true
        type: choice
        options:
          - 'dev'
          - 'uat'
          - 'train'
          - 'prod'
        default: 'dev'

permissions:
  contents: write
  pull-requests: write

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: master
          head: webdev0065-patch-1
          title: 'Auto PR from webdev0065-patch-1 to master'
          body: |
            This PR was automatically created by GitHub Actions
            to merge changes from `webdev0065-patch-1` into `master`.

            **Deployment context:**
            - Exported from: `${{ inputs.exported_resources_env }}`
            - Target environment: `${{ inputs.target_env }}`
            - Operation: `${{ inputs['plan-apply-option'] }}`
