name: Auto PR to master

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Source branch to create PR from'
        required: true
        type: choice
        options:
          - 'webdev0065-patch-1'
          - 'feature-xyz'
          - 'bugfix-123'
        default: 'webdev0065-patch-1'

      draft:
        description: 'Create pull request as draft?'
        required: true
        type: boolean
        default: false

      exported_resources_env:
        description: 'Source environment where resources were originally exported from'
        required: true
        type: choice
        options:
          - 'dev'
          - 'uat'
          - 'train'
          - 'prod'
        default: 'dev'

      plan-apply-option:
        description: 'Choose to plan and apply or only plan'
        required: true
        type: choice
        options:
          - 'plan and apply'
          - 'plan only'
        default: 'plan and apply'

      target_env:
        description: 'Target environment to plan/apply to'
        required: true
        type: choice
        options:
          - 'dev'
          - 'uat'
          - 'train'
          - 'prod'
        default: 'dev'

permissions:
  contents: write
  pull-requests: write

jobs:
  create-pull-request:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: master
          head: ${{ inputs.branch }}
          title: "Auto PR from ${{ inputs.branch }} to master"
          body: |
            This PR was automatically created by GitHub Actions.
            - Branch: `${{ inputs.branch }}`
            - Exported from: `${{ inputs.exported_resources_env }}`
            - Target: `${{ inputs.target_env }}`
            - Mode: `${{ inputs['plan-apply-option'] }}`
          draft: ${{ inputs.draft }}
